from app.models.schemas import JiraProject, JiraSprint, JiraIssue, JiraComment

DEMO_PROJECTS: list[JiraProject] = [
    JiraProject(key="PLAT", name="Platform Core", lead="Sarah Chen"),
    JiraProject(key="MOBILE", name="Mobile App", lead="Marcus Johnson"),
]

DEMO_SPRINTS: dict[str, list[JiraSprint]] = {
    "PLAT": [
        JiraSprint(
            id=101,
            name="Sprint 14 - Auth Overhaul",
            state="active",
            startDate="2026-07-14",
            endDate="2026-07-28",
        ),
        JiraSprint(
            id=100,
            name="Sprint 13 - API Performance",
            state="closed",
            startDate="2026-06-30",
            endDate="2026-07-13",
        ),
    ],
    "MOBILE": [
        JiraSprint(
            id=201,
            name="Sprint 8 - Push Notifications",
            state="active",
            startDate="2026-07-14",
            endDate="2026-07-28",
        ),
    ],
}

DEMO_ISSUES: dict[int, list[JiraIssue]] = {
    101: [
        JiraIssue(
            key="PLAT-142",
            summary="Implement OAuth2 PKCE flow for mobile clients",
            status="Done",
            priority="High",
            assignee="Sarah Chen",
            issueType="Story",
            created="2026-07-14",
            updated="2026-07-22",
            labels=["auth", "security"],
            comments=[
                JiraComment(author="Sarah Chen", body="PKCE implementation complete. All test cases passing.", created="2026-07-22"),
                JiraComment(author="David Park", body="Security review approved. Ready for merge.", created="2026-07-22"),
            ],
        ),
        JiraIssue(
            key="PLAT-143",
            summary="Migrate session store from Redis to encrypted JWT",
            status="Done",
            priority="High",
            assignee="David Park",
            issueType="Story",
            created="2026-07-14",
            updated="2026-07-21",
            labels=["auth", "infrastructure"],
            comments=[
                JiraComment(author="David Park", body="JWT rotation strategy implemented with 15-min access tokens.", created="2026-07-21"),
            ],
        ),
        JiraIssue(
            key="PLAT-144",
            summary="Add rate limiting to authentication endpoints",
            status="Done",
            priority="Medium",
            assignee="Alex Rivera",
            issueType="Task",
            created="2026-07-15",
            updated="2026-07-20",
            labels=["auth", "security"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-145",
            summary="Update API documentation for new auth flow",
            status="Done",
            priority="Low",
            assignee="Maria Lopez",
            issueType="Task",
            created="2026-07-16",
            updated="2026-07-23",
            labels=["documentation"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-146",
            summary="Implement refresh token rotation with reuse detection",
            status="In Progress",
            priority="High",
            assignee="Sarah Chen",
            issueType="Story",
            created="2026-07-15",
            updated="2026-07-25",
            labels=["auth", "security"],
            comments=[
                JiraComment(author="Sarah Chen", body="Reuse detection logic is done. Working on the invalidation cascade now.", created="2026-07-25"),
            ],
        ),
        JiraIssue(
            key="PLAT-147",
            summary="Add multi-factor authentication support",
            status="In Progress",
            priority="High",
            assignee="David Park",
            issueType="Story",
            created="2026-07-16",
            updated="2026-07-24",
            labels=["auth", "feature"],
            comments=[
                JiraComment(author="David Park", body="TOTP implementation done. SMS fallback still pending vendor integration.", created="2026-07-24"),
            ],
        ),
        JiraIssue(
            key="PLAT-148",
            summary="Write integration tests for OAuth2 flow",
            status="In Progress",
            priority="Medium",
            assignee="Alex Rivera",
            issueType="Task",
            created="2026-07-17",
            updated="2026-07-25",
            labels=["testing", "auth"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-149",
            summary="SSO integration with enterprise IdP (Okta/Azure AD)",
            status="To Do",
            priority="Medium",
            assignee="Maria Lopez",
            issueType="Story",
            created="2026-07-18",
            updated="2026-07-18",
            labels=["auth", "enterprise"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-150",
            summary="Audit logging for all authentication events",
            status="To Do",
            priority="Medium",
            assignee=None,
            issueType="Story",
            created="2026-07-18",
            updated="2026-07-18",
            labels=["auth", "compliance"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-151",
            summary="Token encryption at rest - blocked by KMS provisioning",
            status="Blocked",
            priority="High",
            assignee="David Park",
            issueType="Task",
            created="2026-07-15",
            updated="2026-07-23",
            labels=["auth", "security", "blocked"],
            comments=[
                JiraComment(author="David Park", body="Waiting on infrastructure team to provision KMS keys. ETA unclear.", created="2026-07-23"),
                JiraComment(author="Sarah Chen", body="Escalated to VP Eng. Should be unblocked by Monday.", created="2026-07-24"),
            ],
            blockedBy="Infra team KMS key provisioning (external dependency)",
        ),
        JiraIssue(
            key="PLAT-152",
            summary="Performance regression in login flow after JWT migration",
            status="Blocked",
            priority="Critical",
            assignee="Alex Rivera",
            issueType="Bug",
            created="2026-07-22",
            updated="2026-07-25",
            labels=["auth", "performance", "regression"],
            comments=[
                JiraComment(author="Alex Rivera", body="P95 latency increased from 120ms to 380ms. Root cause is the synchronous key lookup. Need async key cache.", created="2026-07-25"),
            ],
            blockedBy="Requires architecture decision on key caching strategy",
        ),
        JiraIssue(
            key="PLAT-153",
            summary="Deprecate legacy API key authentication",
            status="To Do",
            priority="Low",
            assignee=None,
            issueType="Task",
            created="2026-07-20",
            updated="2026-07-20",
            labels=["auth", "deprecation"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-154",
            summary="Fix CORS configuration for new auth callback URLs",
            status="Done",
            priority="Medium",
            assignee="Alex Rivera",
            issueType="Bug",
            created="2026-07-19",
            updated="2026-07-20",
            labels=["auth", "bugfix"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-155",
            summary="Client SDK update for new auth endpoints",
            status="In Progress",
            priority="Medium",
            assignee="Maria Lopez",
            issueType="Task",
            created="2026-07-21",
            updated="2026-07-25",
            labels=["sdk", "auth"],
            comments=[
                JiraComment(author="Maria Lopez", body="Python and JS SDKs updated. Go SDK in progress.", created="2026-07-25"),
            ],
        ),
    ],
    100: [
        JiraIssue(
            key="PLAT-130",
            summary="Optimize database connection pooling",
            status="Done",
            priority="High",
            assignee="David Park",
            issueType="Story",
            created="2026-06-30",
            updated="2026-07-10",
            labels=["performance"],
            comments=[],
        ),
        JiraIssue(
            key="PLAT-131",
            summary="Implement response caching for read-heavy endpoints",
            status="Done",
            priority="Medium",
            assignee="Sarah Chen",
            issueType="Story",
            created="2026-07-01",
            updated="2026-07-12",
            labels=["performance", "caching"],
            comments=[],
        ),
    ],
    201: [
        JiraIssue(
            key="MOBILE-89",
            summary="Implement push notification service integration",
            status="In Progress",
            priority="High",
            assignee="Marcus Johnson",
            issueType="Story",
            created="2026-07-14",
            updated="2026-07-25",
            labels=["notifications", "feature"],
            comments=[
                JiraComment(author="Marcus Johnson", body="FCM integration complete. APNs still in progress.", created="2026-07-25"),
            ],
        ),
        JiraIssue(
            key="MOBILE-90",
            summary="Design notification preferences UI",
            status="Done",
            priority="Medium",
            assignee="Lisa Wang",
            issueType="Task",
            created="2026-07-14",
            updated="2026-07-18",
            labels=["design", "notifications"],
            comments=[],
        ),
        JiraIssue(
            key="MOBILE-91",
            summary="Notification grouping and batching logic",
            status="To Do",
            priority="Medium",
            assignee="Marcus Johnson",
            issueType="Story",
            created="2026-07-16",
            updated="2026-07-16",
            labels=["notifications"],
            comments=[],
        ),
    ],
}
